### ISSUE TITLE
Gradle Sync is failing

### ISSUE THREAD

**Issue by justincbeck** [Isaofmany/StopWatch#1]
The project should just run right out of the box. Using Android Studio 1.5 with Java 1.8.0_31-b13 I get the following error when I load up the project:

```Error:Cause: failed to find target with hash string 'android-22' in: /Users/jbeck/Library/Android/sdk```

 Can you fix this for me?

**Comment by Isaofmany** [comment]
Yes I just arrived home I will fix it.

**Comment by Isaofmany** [comment]
Hi Justin,

    To fix this either I can lower the minimum sdk to an sdk that you have
in your environment or you would have to install have to install the
Android 5.1 SDK.  Is it late for a phone call?

Best,

Randy Richardson

**Comment by justincbeck** [comment]
I’m installing Android SDK 5.1.1 - Stand by.

**Comment by Isaofmany** [comment]
Ok I also just pushed a version that uses a lower API.  While you review
that I will see if I can fix my editText problem before you finish.

**Comment by justincbeck** [comment]
It builds now. I had 6.0 installed but not 5.1. That error message is misleading.


Anyway…  Looks like the emulator fails to load which is an issue with my environment and not your code. I’ll look at it tomorrow on my actual device when I’m in the office.


I’ll pull from GH before I check it out in case you’ve got a fix.


Also, you should close out that issue I created on GH. :)


Thanks.

**Comment by Isaofmany** [comment]
Ok that will give me time to add some things I wanted to include, I'm
trying to make the best impression possible give the time.

Thank you,

Randy

**Comment by justincbeck** [comment]
Sounds good. Thanks Randy.
