### ISSUE TITLE
There's something going on with the fractions of a second

### ISSUE THREAD

**Issue by justincbeck** [Isaofmany/StopWatch#3]
When the clock is running, the tenths count in the far right cell and the next cell over (where the tenths SHOULD be) just flips to 1 as the tenths reach 10. 

The first cell after the decimal should contain tenths of a second that go from 0 to 9 and the last cell should contain hundredths of a second that go from 0 to 9 for each tenth of a second.

**Comment by Isaofmany** [comment]
I built it to reset every 1/10of a second, I will change this.
